### ISSUE TITLE
<v-icon> not working

### ISSUE THREAD

**Issue by nengine** [CodyBontecou/nuxt3-and-vuetify#1]
Icon does not show when I use 
```html
<v-icon>mdi-home</v-icon>  
```
If you have any suggestions please.

**Comment by CodyBontecou** [comment]
Hi @nengine 

Take a look at https://github.com/nuxt/framework/discussions/1183#discussioncomment-2682117.

It should work after doing the following:
1. `yarn add mdi`
2. Adding the following configuration to your nuxt.config
```js
import {defineNuxtConfig} from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    css: [
        ....
        'mdi/css/materialdesignicons.min.css',
        ...
    ],
})
```
3.

**Comment by CodyBontecou** [comment]
@nengine The latest [commit](https://github.com/CodyBontecou/nuxt3-and-vuetify/commit/b44c0150b5e154ed50362e83931e0ebe4895692f) shows this added. I was able to test the above setup and it works :)

**Comment by nengine** [comment]
Many thanks @CodyBontecou .  Very much appreciated.
