### ISSUE TITLE
Theme Color ?

### ISSUE THREAD

**Issue by kaboume** [CodyBontecou/nuxt3-and-vuetify#10]
Hi,
Do you know how to change the colors theme ?
Thanks

**Comment by kaboume** [comment]
I tried but it didn't worked

```
const vuetify = createVuetify({
    components,
    directives,
    theme: {
      defaultTheme: 'myCustomTheme',
      themes: {
        myCustomTheme: {
          primary: '#b53f3f',
          secondary: '#b0bec5',
          accent: '#8c9eff',
          error: '#b71c1c',
        },
      },
    },
  })
```

**Comment by CodyBontecou** [comment]
Hey Kaboume, you need to `export default createVuetify({...})` rather than define it in a variable.

[https://next.vuetifyjs.com/en/features/theme/](https://next.vuetifyjs.com/en/features/theme/)

**Comment by kaboume** [comment]
Thank you !
