### ISSUE TITLE
peer dependencies warning when using the tutorial.

### ISSUE THREAD

**Issue by erondpowell** [CodyBontecou/nuxt3-and-vuetify#5]
Hey Cody, I was following your tutorial and got an error trying to bring in the icons. Any idea why that path is causing this 500?

<img width="1454" alt="Screenshot 2022-11-02 at 12 33 38 AM" src="https://user-images.githubusercontent.com/62306630/199406379-6d3d6e38-9d6a-4e14-98b1-8a27c2a82056.png">

**Comment by CodyBontecou** [comment]
Hey @erondpowell try 
```
npm install @mdi/font
```
```
export default defineNuxtConfig({
    css: [
        ....
        '@mdi/font/css/materialdesignicons.min.css',
        ...
    ],
})
```

**Comment by erondpowell** [comment]
thx cody, trying soon

**Comment by erondpowell** [comment]
another thought. I can't seem to find the original tutorial that led me to this repo. 
While it isn't necessary, it might be kinda nice to have it cross linked in the readme.md
Just ideas 🍨

**Comment by CodyBontecou** [comment]
Haha good idea. Here's the blog post - https://codybontecou.com/how-to-use-vuetify-with-nuxt-3.html
