### ISSUE TITLE
Date picker not showing

### ISSUE THREAD

**Issue by dimunyo** [CodyBontecou/nuxt3-and-vuetify#8]
Hi Cody, All other components that I tried works fine but somehow v-date-picker is not showing/working

this is my code for app.vue

![image](https://user-images.githubusercontent.com/55717823/202596446-c860ddc8-a666-4e29-a73f-dae5bac81ad7.png)

the warning

![image](https://user-images.githubusercontent.com/55717823/202596334-3637e0ae-d7f7-4ef2-b5e9-5b3cbd6a5867.png)

**Comment by CodyBontecou** [comment]
Hey @dimunyo it looks like the `v-date-picker` component hasn't been released in Vuetify 3.

https://github.com/vuetifyjs/vuetify/issues/14984#issuecomment-1111579118
